### ISSUE TITLE
May I try to convert your SimpleDynoHS to C#?

### ISSUE THREAD

**Issue by vmx17** [jahonen75/SimpleDynoHS#1]
Sorry, this is not issue but I don't know other method to reach you.
Recently I'm interested in power dyno for some small motors and I'll try to make one of it. Mainly I want to use it for RC cars or planes. Because there is no mention about license, I'm asking the title here. Basically, I am a C#/C++ programmer and there is a VisualStudio extension that convert between C# and VisualBasic. Things seems not so smart, the conversion may not be fully automatic. I don't know it can or not, but may I try it based on your code? I'm considering convert this to C# on .Net 8 WinForms.

**Comment by jahonen75** [comment]
I see no reason why not. Please go ahead.

**Comment by vmx17** [comment]
Thank you. I've just made it public at [here](https://github.com/vmx17/SimpleDyno-CS) but not have checked, yet.
